system:
  name: "ChefSync Admin Management System"
  version: "2.0.0"
  environment: "development"
  
features:
  user_management: true
  order_management: true
  food_management: true
  analytics: true
  notifications: true
  communications: true
  approvals: true
  system_monitoring: true
  
security:
  admin_session_timeout: 3600
  max_login_attempts: 5
  password_policy:
    min_length: 8
    require_special_chars: true
    require_numbers: true
    require_uppercase: true
  
api:
  rate_limiting:
    enabled: true
    requests_per_minute: 100
    burst_limit: 200
  
  caching:
    enabled: true
    ttl: 300
    max_size: 1000
  
database:
  connection_pool:
    min_connections: 5
    max_connections: 20
    timeout: 30
  
  query_optimization:
    enabled: true
    slow_query_threshold: 1000
  
monitoring:
  health_checks:
    enabled: true
    interval: 60
    timeout: 30
  
  metrics:
    enabled: true
    collection_interval: 60
    retention_days: 30
  
  alerts:
    enabled: true
    channels: ["email", "webhook"]
    thresholds:
      cpu_usage: 80
      memory_usage: 85
      disk_usage: 90
      error_rate: 5
  
logging:
  level: "info"
  format: "json"
  output: "file"
  max_size: "100MB"
  max_files: 10
  
  audit:
    enabled: true
    log_admin_actions: true
    log_user_actions: true
    retention_days: 90