# ChefSync Kitchen Management System Configuration
# This file contains system-wide configuration settings

system:
  name: "ChefSync Kitchen Management"
  version: "1.0.0"
  environment: "development"
  debug: false
  timezone: "UTC"
  language: "en"
  
# Feature Flags
features:
  user_management: true
  order_management: true
  food_management: true
  analytics: true
  notifications: true
  reporting: true
  system_monitoring: true
  backup_management: true
  maintenance_mode: true
  audit_logging: true
  
# Security Configuration
security:
  admin_session_timeout: 3600  # 1 hour in seconds
  max_login_attempts: 5
  login_lockout_duration: 900  # 15 minutes in seconds
  password_policy:
    min_length: 8
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special_chars: true
    password_history: 5
  jwt_settings:
    access_token_lifetime: 3600  # 1 hour
    refresh_token_lifetime: 604800  # 7 days
    algorithm: "HS256"
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "http://localhost:5173"
      - "http://localhost:8080"
      - "http://localhost:8081"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed_headers:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"

# Database Configuration
database:
  engine: "mysql"
  name: "chefsync_kitchen"
  host: "localhost"
  port: 3306
  user: "root"
  password: "password"
  charset: "utf8mb4"
  collation: "utf8mb4_unicode_ci"
  connection_pool:
    min_connections: 5
    max_connections: 20
    connection_timeout: 30

# Cache Configuration
cache:
  backend: "redis"
  host: "localhost"
  port: 6379
  db: 0
  password: ""
  default_timeout: 300
  key_prefix: "chefsync:"

# Email Configuration
email:
  backend: "smtp"
  host: "smtp.gmail.com"
  port: 587
  use_tls: true
  username: ""
  password: ""
  from_email: "noreply@chefsync.com"
  from_name: "ChefSync Kitchen"

# File Storage Configuration
storage:
  backend: "local"  # local, s3, gcs
  local_path: "/uploads"
  max_file_size: 10485760  # 10MB in bytes
  allowed_extensions:
    - "jpg"
    - "jpeg"
    - "png"
    - "gif"
    - "pdf"
    - "doc"
    - "docx"
  s3:
    bucket_name: ""
    region: "us-east-1"
    access_key: ""
    secret_key: ""

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console:
      enabled: true
      level: "INFO"
    file:
      enabled: true
      level: "DEBUG"
      filename: "logs/chefsync.log"
      max_size: 10485760  # 10MB
      backup_count: 5
    admin_log:
      enabled: true
      level: "INFO"
      filename: "logs/admin.log"
      max_size: 10485760  # 10MB
      backup_count: 10

# Monitoring Configuration
monitoring:
  enabled: true
  metrics:
    enabled: true
    endpoint: "/metrics"
  health_check:
    enabled: true
    endpoint: "/health"
    timeout: 30
  performance:
    enabled: true
    slow_query_threshold: 1000  # milliseconds
    memory_usage_threshold: 80  # percentage

# Backup Configuration
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention_days: 30
  compression: true
  encryption: true
  destinations:
    - "local"
    - "s3"  # optional
  local_path: "/backups"
  s3:
    bucket: "chefsync-backups"
    region: "us-east-1"

# API Configuration
api:
  version: "v1"
  rate_limit:
    enabled: true
    requests_per_minute: 1000
    burst_limit: 100
  pagination:
    default_size: 25
    max_size: 100
  timeout: 30
  retry_attempts: 3

# Admin Dashboard Configuration
admin:
  dashboard:
    refresh_interval: 30000  # milliseconds
    auto_refresh: true
    default_view: "overview"
  notifications:
    enabled: true
    sound: true
    popup: true
    email: true
  audit:
    enabled: true
    retention_days: 90
    log_level: "INFO"
  maintenance:
    enabled: true
    message: "System is under maintenance. Please try again later."
    allowed_ips: []  # Empty means no IP restrictions

# Business Logic Configuration
business:
  order:
    auto_cancel_timeout: 1800  # 30 minutes in seconds
    max_items_per_order: 50
    min_order_amount: 0
    delivery_fee: 2.99
    tax_rate: 0.08  # 8%
  user:
    max_orders_per_day: 10
    account_verification_required: true
    profile_completion_required: true
  chef:
    approval_required: true
    max_food_items: 100
    rating_threshold: 4.0
  delivery:
    max_delivery_radius: 10  # miles
    delivery_time_estimate: 30  # minutes
    tracking_enabled: true
