# Generated by Django 5.2.5 on 2025-09-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_convert_profile_to_cloudinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether the chef is currently available for orders'),
        ),
    ]
