# Generated by Django 4.2.7 on 2025-09-25 21:49

from django.conf import settings
from django.db import migrations, models, connection
import django.db.models.deletion


def check_and_remove_columns(apps, schema_editor):
    """Safely remove columns only if they exist"""
    with connection.cursor() as cursor:
        # Get current columns
        cursor.execute("DESCRIBE delivery_profiles")
        columns = [col[0] for col in cursor.fetchall()]
        
        # Columns to potentially remove
        columns_to_remove = ['insurance_info', 'total_earnings', 'vehicle_number']
        
        for column in columns_to_remove:
            if column in columns:
                cursor.execute(f"ALTER TABLE delivery_profiles DROP COLUMN {column}")
                print(f"Removed column: {column}")
            else:
                print(f"Column {column} does not exist, skipping removal")


def reverse_add_columns(apps, schema_editor):
    """Add back the columns if needed during reverse migration"""
    with connection.cursor() as cursor:
        # Check which columns are missing and add them back
        cursor.execute("DESCRIBE delivery_profiles")
        columns = [col[0] for col in cursor.fetchall()]
        
        if 'insurance_info' not in columns:
            cursor.execute("ALTER TABLE delivery_profiles ADD COLUMN insurance_info JSON")
        
        if 'total_earnings' not in columns:
            cursor.execute("ALTER TABLE delivery_profiles ADD COLUMN total_earnings DECIMAL(10,2) DEFAULT 0.00")
            
        if 'vehicle_number' not in columns:
            cursor.execute("ALTER TABLE delivery_profiles ADD COLUMN vehicle_number VARCHAR(20) DEFAULT ''")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_convert_profile_to_cloudinary'),
    ]

    operations = [
        migrations.RunPython(
            check_and_remove_columns,
            reverse_add_columns
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
