# Generated by Django 5.2.5 on 2025-09-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_approval_status_to_delivery_profile'),
        ('users', '0002_auto_20250920_2024'),
    ]

    operations = [
    ]
