# Generated by Django 4.2.7 on 2025-09-27 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_deliveryprofile_insurance_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='insurance_info',
        ),
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='total_earnings',
        ),
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='vehicle_number',
        ),
    ]
