# Generated by Django 5.2.5 on 2025-09-20 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactivitylog',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminbackuplog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['is_read', 'is_active'], name='admin_manag_is_read_a3b2f7_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['notification_type', 'priority'], name='admin_manag_notific_dd1d51_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['created_at'], name='admin_manag_created_50babe_idx'),
        ),
        migrations.AddField(
            model_name='adminsystemsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='systemhealthmetric',
            index=models.Index(fields=['metric_type', 'timestamp'], name='admin_manag_metric__7c0e6e_idx'),
        ),
        migrations.AddIndex(
            model_name='systemhealthmetric',
            index=models.Index(fields=['timestamp'], name='admin_manag_timesta_cc6a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['admin', 'timestamp'], name='admin_manag_admin_i_4b1cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['action', 'resource_type'], name='admin_manag_action_b5f7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['timestamp'], name='admin_manag_timesta_ee3a49_idx'),
        ),
        migrations.AddIndex(
            model_name='adminbackuplog',
            index=models.Index(fields=['status', 'backup_type'], name='admin_manag_status_aa0462_idx'),
        ),
        migrations.AddIndex(
            model_name='adminbackuplog',
            index=models.Index(fields=['started_at'], name='admin_manag_started_29afdf_idx'),
        ),
        migrations.AddIndex(
            model_name='adminsystemsettings',
            index=models.Index(fields=['category', 'is_public'], name='admin_manag_categor_e021f3_idx'),
        ),
        migrations.AddIndex(
            model_name='adminsystemsettings',
            index=models.Index(fields=['key'], name='admin_manag_key_94a804_idx'),
        ),
    ]
