# Generated by Django 5.2.5 on 2025-09-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('system_alert', 'System Alert'), ('user_activity', 'User Activity'), ('order_update', 'Order Update'), ('payment_issue', 'Payment Issue'), ('security_event', 'Security Event'), ('maintenance', 'Maintenance'), ('backup', 'Backup'), ('performance', 'Performance'), ('communication_response', 'Communication Response'), ('communication_received', 'Communication Received')], max_length=25),
        ),
    ]
