# Generated by Django 5.2.5 on 2025-10-01 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivitylog',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_management_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminbackuplog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_management_backup_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminsystemsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_management_system_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
