# Generated by Django 4.2.7 on 2025-10-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_useraddress_state_alter_bulkorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup')], default='delivery', help_text='Whether this is a delivery or pickup order', max_length=20),
        ),
    ]
