# Generated by Django 4.2.7 on 2025-09-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='OrderItem',
        ),
    ]
