# Generated by Django 5.2.5 on 2025-10-24 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_useraddress_state_alter_bulkorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_orders', to='orders.order'),
        ),
    ]
