# Generated by Django 5.2.5 on 2025-09-26 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status_alter_orderstatushistory_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash on Delivery')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='BulkOrder',
            fields=[
                ('bulk_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('total_quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_bulk_orders', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bulk_order', to='orders.order')),
            ],
            options={
                'db_table': 'bulk_orders',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BulkOrderAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bulk_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignments', to='orders.bulkorder')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bulk_order_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulk_order_assignments',
                'managed': True,
                'unique_together': {('bulk_order', 'chef')},
            },
        ),
    ]
