# Generated by Django 4.2.7 on 2025-09-28 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('orders', '0007_add_user_address_and_delivery_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address_new',
            field=models.ForeignKey(blank=True, help_text='New address system reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='users.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='kitchen_location',
            field=models.ForeignKey(blank=True, help_text='Kitchen location for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_orders', to='users.address'),
        ),
    ]
