# Generated by Django 4.2.7 on 2025-09-28 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("orders", "0002_deliverychat_deliveryissue_deliverylog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_address_new_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="New address system reference",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="kitchen_location_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Kitchen location for this order",
                null=True,
            ),
        ),
    ]
