# Generated by Django 5.2.5 on 2025-10-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_bulkorder_order'),
        ('orders', '0007_create_delivery_chat'),
    ]

    operations = [
    ]
