# Generated by Django 5.2.5 on 2025-10-24 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_merge_20251024_1918'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('work_distribution', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('response_reason', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'CollaborationRequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='deliverychat',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='bulkorder',
            name='BulkOrder_custome_idx',
        ),
        migrations.RenameIndex(
            model_name='bulkorder',
            new_name='BulkOrder_chef_id_38ba8e_idx',
            old_name='BulkOrder_chef_st_idx',
        ),
        migrations.RemoveField(
            model_name='bulkorder',
            name='customer',
        ),
        migrations.AlterField(
            model_name='bulkorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bulkorder',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this bulk order (usually same as customer)', on_delete=django.db.models.deletion.CASCADE, related_name='created_bulk_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bulkorder',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about the bulk order', null=True),
        ),
        migrations.AlterField(
            model_name='bulkorder',
            name='order_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='bulkorder',
            index=models.Index(fields=['created_by', 'status'], name='BulkOrder_created_7ba674_idx'),
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='bulk_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_requests', to='orders.bulkorder'),
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='from_user',
            field=models.ForeignKey(help_text='User who sent the collaboration request', on_delete=django.db.models.deletion.CASCADE, related_name='sent_collaboration_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='to_user',
            field=models.ForeignKey(help_text='User who is invited to collaborate', on_delete=django.db.models.deletion.CASCADE, related_name='received_collaboration_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
