# Generated by Django 5.2.5 on 2025-10-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_merge_20251024_1548"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryreview",
            name="admin_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryreview",
            name="response_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
