# Generated by Django 5.2.5 on 2025-10-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_merge_20251024_1548'),
        ('orders', '0012_fix_bulkorderassignment_timestamps'),
    ]

    operations = [
    ]
