# Generated by Django 4.2.7 on 2025-10-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_bulkorderassignment_updated_at_and_more'),
    ]

    operations = [
        # No operations needed - this is a no-op migration to resolve state inconsistency
    ]
