# Generated by Django 5.2.5 on 2025-10-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_add_admin_response_to_delivery_review'),
        ('orders', '0015_bulkorderassignment_updated_at'),
    ]

    operations = [
    ]
