# Generated by Django 4.2.7 on 2025-10-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_add_admin_response_to_delivery_review'),
        ('orders', '0015_bulkorderassignment_updated_at'),
    ]

    operations = [
    ]
