# Generated by Django 5.2.5 on 2025-10-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_merge_20251025_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkorderassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulkorder',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, unique=True),
        ),
    ]
