# Generated by Django 5.2.5 on 2025-10-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_merge_20251025_1124'),
        ('orders', '0016_merge_20251025_1227'),
        ('orders', '0017_bulkorderassignment_updated_at_and_more'),
    ]

    operations = [
    ]
