# Generated by Django 5.2.5 on 2025-10-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_merge_20251025_1326'),
        ('orders', '0019_alter_order_status_alter_orderstatushistory_status'),
    ]

    operations = [
    ]
