# Generated by Django 5.2.5 on 2025-09-20 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreview',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_reviews', to='orders.order'),
        ),
        migrations.AlterUniqueTogether(
            name='foodcategory',
            unique_together={('cuisine', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='food',
            unique_together={('chef', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='foodreview',
            unique_together={('customer', 'food', 'order')},
        ),
    ]
