# Generated by Django 5.2.5 on 2025-10-06 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreview',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_reviews', to='orders.order'),
        ),
        migrations.AddField(
            model_name='foodreview',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='food.foodprice'),
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='food.foodprice'),
        ),
        migrations.AlterUniqueTogether(
            name='foodcategory',
            unique_together={('cuisine', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='foodprice',
            unique_together={('food', 'size', 'cook')},
        ),
        migrations.AlterUniqueTogether(
            name='foodreview',
            unique_together={('customer', 'price', 'order')},
        ),
    ]
