# Generated by Django 5.2.5 on 2025-09-25 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
    ]
