# Generated by Django 5.2.5 on 2025-09-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='food',
            table='foods',
        ),
    ]
