# Generated by Django 5.2.5 on 2025-09-22 04:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodreview',
            unique_together={('customer', 'price', 'order')},
        ),
    ]
