# Generated by Django 4.2.7 on 2025-10-22 09:30

import apps.food.cloudinary_fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks')], max_length=20)),
                ('menu_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_price_per_person', models.DecimalField(decimal_places=2, help_text='Base price per person in rupees', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('availability_status', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('min_persons', models.PositiveIntegerField(default=10, help_text='Minimum number of persons for this bulk menu')),
                ('max_persons', models.PositiveIntegerField(default=100, help_text='Maximum number of persons for this bulk menu')),
                ('advance_notice_hours', models.PositiveIntegerField(default=24, help_text='Hours of advance notice required for ordering')),
                ('image', apps.food.cloudinary_fields.CloudinaryImageField(blank=True, help_text='Main image for the bulk menu', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bulk_menus', to=settings.AUTH_USER_MODEL)),
                ('chef', models.ForeignKey(limit_choices_to={'role': 'cook'}, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_menus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulk_menus',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_optional', models.BooleanField(default=False, help_text='Whether this item is optional (customers can choose to add)')),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional cost if this item is selected (for optional items)', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('spice_level', models.CharField(blank=True, choices=[('mild', 'Mild'), ('medium', 'Medium'), ('hot', 'Hot'), ('very_hot', 'Very Hot')], max_length=20, null=True)),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bulk_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food.bulkmenu')),
            ],
            options={
                'db_table': 'bulk_menu_items',
                'ordering': ['sort_order', 'item_name'],
                'unique_together': {('bulk_menu', 'item_name')},
            },
        ),
        migrations.AddIndex(
            model_name='bulkmenu',
            index=models.Index(fields=['meal_type', 'approval_status'], name='bulk_menus_meal_ty_da71d4_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkmenu',
            index=models.Index(fields=['chef', 'availability_status'], name='bulk_menus_chef_id_c40fdc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bulkmenu',
            unique_together={('chef', 'meal_type', 'menu_name')},
        ),
    ]
