# Generated by Django 5.2.5 on 2025-09-22 09:23

from django.db import migrations, models


# Define the old field locally since apps.users.fields was removed
class LongBlobImageField(models.TextField):
    """Local copy of the old LongBlobImageField for migration compatibility"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_foodreview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=LongBlobImageField(blank=True, help_text='Food image', null=True),
        ),
        migrations.AddField(
            model_name='foodprice',
            name='preparation_time',
            field=models.PositiveIntegerField(default=15, help_text='Preparation time in minutes for this size'),
        ),
    ]
