# Generated by Django 4.2.7 on 2025-09-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_food_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='food',
            table='Food',
        ),
    ]
