# Generated by Django 5.2.5 on 2025-10-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_bulkmenu_bulkmenuitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkmenuitem',
            name='is_gluten_free',
        ),
        migrations.RemoveField(
            model_name='bulkmenuitem',
            name='is_vegan',
        ),
    ]
