# Generated by Django 5.2.5 on 2025-09-22 09:23

import apps.users.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_foodreview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=apps.users.fields.LongBlobImageField(blank=True, help_text='Food image', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='foodprice',
            name='preparation_time',
            field=models.PositiveIntegerField(default=15, help_text='Preparation time in minutes for this size'),
        ),
    ]
