# Generated by Django 4.2.7 on 2025-09-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_food_table'),
        ('food', '0004_food_image_foodprice_preparation_time'),
    ]

    operations = [
    ]
