# Generated by Django 4.2.7 on 2025-09-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_food_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='foodimage',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='foodimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for accessibility', max_length=100),
        ),
        migrations.AddField(
            model_name='foodimage',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for management', max_length=200),
        ),
        migrations.AddField(
            model_name='foodimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for the main image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='foodimage',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for thumbnail', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='foodimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
