# Generated by Django 4.2.7 on 2025-09-24 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_merge_20250923_1316'),
        ('food', '0005_update_foodimage_to_cloudinary'),
    ]

    operations = [
    ]
