# Generated by Django 4.2.7 on 2025-09-24 23:56

import apps.food.cloudinary_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_merge_20250925_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='image',
            field=apps.food.cloudinary_fields.CloudinaryImageField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=apps.food.cloudinary_fields.CloudinaryImageField(blank=True, help_text='Food image', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='image',
            field=apps.food.cloudinary_fields.CloudinaryImageField(blank=True, max_length=500, null=True),
        ),
    ]
