# Generated by Django 4.2.7 on 2025-09-26 00:33

from django.db import migrations, models


def migrate_primary_images_to_food(apps, schema_editor):
    """Migrate primary images from FoodImage to Food model"""
    Food = apps.get_model('food', 'Food')
    FoodImage = apps.get_model('food', 'FoodImage')
    
    # Update Food records with their primary image URL
    for food in Food.objects.all():
        try:
            # Get the primary image for this food item
            primary_image = FoodImage.objects.filter(food=food, is_primary=True).first()
            if not primary_image:
                # If no primary image, get the first image
                primary_image = FoodImage.objects.filter(food=food).first()
            
            if primary_image and primary_image.image_url:
                # Update the food's image field with the Cloudinary URL
                food.image = primary_image.image_url
                food.save()
                print(f"Migrated primary image for {food.name}: {primary_image.image_url}")
        except Exception as e:
            print(f"Error migrating image for food {food.name}: {e}")


def reverse_migration(apps, schema_editor):
    """Reverse migration - create FoodImage records from Food.image"""
    Food = apps.get_model('food', 'Food')
    FoodImage = apps.get_model('food', 'FoodImage')
    
    for food in Food.objects.filter(image__isnull=False).exclude(image=''):
        try:
            FoodImage.objects.create(
                food=food,
                image_url=str(food.image),
                is_primary=True,
                sort_order=0
            )
        except Exception as e:
            print(f"Error creating FoodImage for {food.name}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_convert_to_cloudinary_images'),
    ]

    operations = [
        # First, migrate the data
        migrations.RunPython(
            migrate_primary_images_to_food,
            reverse_migration,
        ),
        # Then remove the FoodImage model
        migrations.DeleteModel(
            name='FoodImage',
        ),
    ]
