# Generated by Django 5.2.5 on 2025-09-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_convert_to_cloudinary_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodprice',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large'), ('Family Size', 'Family Size')], max_length=15),
        ),
    ]
