# Generated by Django 4.2.7 on 2025-09-26 00:42

import apps.food.cloudinary_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_remove_foodimage_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=apps.food.cloudinary_fields.CloudinaryImageField(blank=True, help_text='Primary food image - uploaded to Cloudinary', max_length=500, null=True),
        ),
    ]
