# Generated by Django 5.2.5 on 2025-10-21 13:30

import apps.food.cloudinary_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_bulkmenu_bulkmenuitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkmenu',
            name='image',
            field=apps.food.cloudinary_fields.CloudinaryImageField(blank=True, help_text='Main image for the bulk menu', max_length=500, null=True),
        ),
    ]
