# Generated by Django 5.2.5 on 2025-09-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('Admin', 'Admin'), ('Customer', 'Customer'), ('Cook', 'Cook'), ('DeliveryAgent', 'DeliveryAgent')], default='Customer', help_text='User role in the system', max_length=20),
        ),
    ]
