# Generated by Django 4.2.7 on 2025-09-22 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwttoken',
            name='campaign_name',
            field=models.CharField(blank=True, help_text='Name of the referral campaign', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jwttoken',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of times this referral token can be used'),
        ),
        migrations.AddField(
            model_name='jwttoken',
            name='referee_reward',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Reward amount for referee', max_digits=10),
        ),
        migrations.AddField(
            model_name='jwttoken',
            name='referrer_reward',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Reward amount for referrer', max_digits=10),
        ),
        migrations.AddField(
            model_name='jwttoken',
            name='used_by',
            field=models.ForeignKey(blank=True, help_text='User who used this referral token', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_referral_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, help_text="User's unique referral code", max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_rewards_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total referral rewards earned', max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_rewards_used',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total referral rewards used', max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_token_used',
            field=models.CharField(blank=True, help_text='Referral token that was used during registration', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='User who referred this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='total_referrals',
            field=models.PositiveIntegerField(default=0, help_text='Total number of successful referrals made by this user'),
        ),
        migrations.AlterField(
            model_name='jwttoken',
            name='token_type',
            field=models.CharField(choices=[('access', 'Access Token'), ('refresh', 'Refresh Token'), ('referral', 'Referral Token')], max_length=10),
        ),
    ]
