# Generated by Django 5.2.5 on 2025-09-25 04:48

import apps.food.cloudinary_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_restore_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Activation status for all users', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=apps.food.cloudinary_fields.CloudinaryImageField(blank=True, max_length=500, null=True),
        ),
    ]
