# Generated by Django 5.2.5 on 2025-09-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_account_locked_user_account_locked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Full address of the user', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('cook', 'Cook'), ('delivery_agent', 'Delivery Agent')], default='customer', help_text='User role in the system', max_length=20),
        ),
    ]
