# Generated by Django 5.2.5 on 2025-09-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('cook', 'Cook'), ('delivery_agent', 'Delivery Agent')], default='customer', help_text='User role in the system', max_length=20),
        ),
    ]
