# Generated by Django 4.2.7 on 2025-09-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_jwttoken_campaign_name_jwttoken_max_uses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('Admin', 'Admin'), ('customer', 'Customer'), ('Customer', 'Customer'), ('cook', 'Cook'), ('Cook', 'Cook'), ('delivery_agent', 'Delivery Agent'), ('DeliveryAgent', 'DeliveryAgent')], default='Customer', help_text='User role in the system', max_length=20),
        ),
    ]
