# Generated by Django 5.2.5 on 2025-09-04 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_address_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='SHA-256 hash of the refresh token', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('device_info', models.CharField(blank=True, help_text='Device/browser information', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RefreshToken',
                'indexes': [models.Index(fields=['token_hash'], name='RefreshToke_token_h_0cdd82_idx'), models.Index(fields=['user', 'is_revoked'], name='RefreshToke_user_id_6434c9_idx'), models.Index(fields=['expires_at'], name='RefreshToke_expires_c7d754_idx')],
            },
        ),
    ]
