# Generated by Django 5.2.5 on 2025-10-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_cook_current_latitude_cook_current_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(blank=True, help_text='Cloudinary URL for user profile image', max_length=500, null=True),
        ),
    ]
