# Generated by Django 5.2.5 on 2025-10-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_cook_current_latitude_cook_current_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cook',
            name='availability_hours',
        ),
        migrations.AddField(
            model_name='cook',
            name='available_days',
            field=models.CharField(blank=True, help_text="Available days (e.g., 'Monday-Friday', 'Weekends', 'Daily')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cook',
            name='available_end_time',
            field=models.TimeField(blank=True, help_text='Daily availability end time', null=True),
        ),
        migrations.AddField(
            model_name='cook',
            name='available_start_time',
            field=models.TimeField(blank=True, help_text='Daily availability start time', null=True),
        ),
    ]
