# Generated by Django 5.2.5 on 2025-10-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_update_cook_availability_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cook',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='available_end_time',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='available_start_time',
        ),
        migrations.AddField(
            model_name='cook',
            name='availability_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
