# Generated by Django 4.2.7 on 2025-09-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_role'),
        ('authentication', '0004_update_role_choices'),
    ]

    operations = [
    ]
