# Generated by Django 5.2.5 on 2025-09-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_update_role_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwttoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration time of the token', null=True),
        ),
        migrations.AlterField(
            model_name='jwttoken',
            name='is_revoked',
            field=models.BooleanField(default=False, help_text='Indicates if the token has been revoked'),
        ),
    ]
