# Generated by Django 5.2.5 on 2025-09-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_refreshtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address to verify', max_length=254)),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0, help_text='Number of verification attempts')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'EmailOTP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'is_verified'], name='EmailOTP_email_732f51_idx'), models.Index(fields=['expires_at'], name='EmailOTP_expires_037692_idx'), models.Index(fields=['otp_code'], name='EmailOTP_otp_cod_89706c_idx')],
            },
        ),
    ]
