# Generated by Django 5.2.5 on 2025-09-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_emailotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailotp',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email OTP', 'verbose_name_plural': 'Email OTPs'},
        ),
        migrations.RemoveIndex(
            model_name='emailotp',
            name='EmailOTP_email_732f51_idx',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='max_attempts',
            field=models.IntegerField(default=3, help_text='Maximum allowed attempts'),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata for the OTP'),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('login', 'Login Verification'), ('transaction', 'Transaction Verification')], default='verification', help_text='Purpose of the OTP', max_length=20),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', help_text='Current status of the OTP', max_length=10),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(db_index=True, help_text='Email address to verify', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the requester', null=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='otp_code',
            field=models.CharField(db_index=True, help_text='6-digit OTP code', max_length=6),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='user_agent',
            field=models.CharField(blank=True, help_text='User agent of the requester', max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['email', 'status'], name='EmailOTP_email_16658b_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['email', 'purpose'], name='EmailOTP_email_e3e38f_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['created_at'], name='EmailOTP_created_b26247_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['status', 'expires_at'], name='EmailOTP_status_a9573a_idx'),
        ),
    ]
