# Generated by Django 4.2.7 on 2025-09-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_merge_0003_alter_user_role_0004_update_role_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwttoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration time of the token', null=True),
        ),
        migrations.AlterField(
            model_name='jwttoken',
            name='is_revoked',
            field=models.BooleanField(default=False, help_text='Indicates if the token has been revoked'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('Admin', 'Admin'), ('customer', 'Customer'), ('Customer', 'Customer'), ('cook', 'Cook'), ('Cook', 'Cook'), ('delivery_agent', 'Delivery Agent'), ('DeliveryAgent', 'DeliveryAgent')], default='Customer', help_text='User role in the system', max_length=20),
        ),
    ]
