# Generated by Django 5.2.5 on 2025-10-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_profile_image'),
        ('authentication', '0005_remove_cook_available_days_and_more'),
    ]

    operations = [
    ]
