# Generated by Django 5.2.5 on 2025-09-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_jwttoken_expires_at_alter_jwttoken_is_revoked'),
        ('authentication', '0006_alter_jwttoken_expires_at_alter_jwttoken_is_revoked_and_more'),
    ]

    operations = [
    ]
