# Generated by Django 5.2.5 on 2025-09-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_emailotp_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailotp',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='emailotp',
            name='EmailOTP_email_16658b_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailotp',
            name='EmailOTP_email_e3e38f_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailotp',
            name='EmailOTP_created_b26247_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailotp',
            name='EmailOTP_status_a9573a_idx',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='max_attempts',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='status',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='verified_at',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(help_text='Email address to verify', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='otp_code',
            field=models.CharField(help_text='6-digit OTP code', max_length=6),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['email', 'is_verified'], name='EmailOTP_email_732f51_idx'),
        ),
    ]
