# Generated by Django 5.2.5 on 2025-10-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_merge_20251025_1247'),
        ('authentication', '0006_merge_20251025_1258'),
    ]

    operations = [
    ]
