# Generated by Django 5.2.5 on 2025-09-04 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_emailotp_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JWTToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='SHA-256 hash of the JWT token', max_length=64, unique=True)),
                ('token_type', models.CharField(choices=[('access', 'Access Token'), ('refresh', 'Refresh Token')], default='access', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('device_info', models.CharField(blank=True, help_text='Device/browser information', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jwt_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'JWTToken',
                'indexes': [models.Index(fields=['token_hash'], name='JWTToken_token_hash_idx'), models.Index(fields=['user', 'is_revoked'], name='JWTToken_user_revoked_idx'), models.Index(fields=['expires_at'], name='JWTToken_expires_idx'), models.Index(fields=['token_type', 'is_revoked'], name='JWTToken_type_revoked_idx')],
            },
        ),
    ]
