# Generated by Django 4.2.7 on 2025-09-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_user_profile_image_cook_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cook',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='deliveryagent',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
