# Generated by Django 5.2.5 on 2025-09-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_jwttoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
        migrations.RemoveField(
            model_name='refreshtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='JWTToken',
        ),
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
