# Generated by Django 5.2.5 on 2025-09-05 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='JWTToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='SHA-256 hash of the token', max_length=64, unique=True)),
                ('token_type', models.CharField(choices=[('access', 'Access Token'), ('refresh', 'Refresh Token')], max_length=10)),
                ('jti', models.CharField(help_text='JWT ID from token payload', max_length=255, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('blacklisted_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jwt_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jwt_tokens',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['user', 'token_type'], name='jwt_tokens_user_id_636378_idx'), models.Index(fields=['token_hash'], name='jwt_tokens_token_h_f75a1b_idx'), models.Index(fields=['jti'], name='jwt_tokens_jti_5d9bd1_idx'), models.Index(fields=['expires_at'], name='jwt_tokens_expires_b82c5c_idx'), models.Index(fields=['is_revoked', 'is_blacklisted'], name='jwt_tokens_is_revo_82f4b5_idx')],
            },
        ),
    ]
