# Generated by Django 5.2.5 on 2025-09-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_user_approval_notes_user_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for the file', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='is_visible_to_admin',
            field=models.BooleanField(default=False, help_text='Whether admin can see this document'),
        ),
    ]
