# Generated by Django 5.2.6 on 2025-09-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_userdocument_cloudinary_public_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdocument',
            name='cloudinary_public_id',
        ),
    ]
