# Generated by Django 5.2.5 on 2025-09-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_cloudinary_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for the file', max_length=255, null=True),
        ),
    ]
