# Generated by Django 5.2.5 on 2025-09-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_add_cloudinary_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='file',
            field=models.URLField(help_text='Document file URL (Cloudinary or local)', max_length=500),
        ),
    ]
