# Generated by Django 5.2.6 on 2025-09-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_userdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='is_single_page_only',
            field=models.BooleanField(default=True, help_text='Whether this document should be single page only'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='max_pages',
            field=models.IntegerField(default=2, help_text='Maximum number of pages allowed (for PDFs)'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='max_file_size_mb',
            field=models.IntegerField(default=5, help_text='Maximum file size in MB'),
        ),
    ]
