# Generated by Django 5.2.6 on 2025-09-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_documenttype_is_single_page_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='local_file_path',
            field=models.CharField(blank=True, help_text='Local file path for PDFs to avoid Cloudinary access issues', max_length=500, null=True),
        ),
    ]
