# Generated by Django 5.2.6 on 2025-09-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_userdocument_local_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='converted_images',
            field=models.JSONField(blank=True, help_text='Metadata for converted images (for PDFs converted to images)', null=True),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='is_pdf_converted',
            field=models.BooleanField(default=False, help_text='Whether this document was converted from PDF to images'),
        ),
    ]
