# Generated by Django 5.2.5 on 2025-09-20 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('feedback', 'Feedback'), ('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('inquiry', 'Inquiry'), ('other', 'Other')], default='feedback', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_communications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='communication_attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communications.communication')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='communications.communicationcategory')),
            ],
            options={
                'verbose_name_plural': 'Communication Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationCategoryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_relations', to='communications.communicationcategory')),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_relations', to='communications.communication')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='communications.communication')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='communications.communication')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_relations', to='communications.communicationtag')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('feedback', 'Feedback Response'), ('complaint', 'Complaint Response'), ('inquiry', 'Inquiry Response'), ('general', 'General Response'), ('resolution', 'Resolution Response'), ('acknowledgment', 'Acknowledgment')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('variables', models.JSONField(default=dict, help_text='Template variables in JSON format')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['communication_type', 'status'], name='communicati_communi_a626e4_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['user', 'created_at'], name='communicati_user_id_881390_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['reference_number'], name='communicati_referen_2e829e_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['priority', 'status'], name='communicati_priorit_728fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationattachment',
            index=models.Index(fields=['communication', 'created_at'], name='communicati_communi_834e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationcategory',
            index=models.Index(fields=['parent', 'is_active'], name='communicati_parent__99e717_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationcategoryrelation',
            index=models.Index(fields=['communication', 'category'], name='communicati_communi_cbef87_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communicationcategoryrelation',
            unique_together={('communication', 'category')},
        ),
        migrations.AddIndex(
            model_name='communicationresponse',
            index=models.Index(fields=['communication', 'created_at'], name='communicati_communi_3d5891_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationresponse',
            index=models.Index(fields=['responder', 'created_at'], name='communicati_respond_f6c79a_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationtag',
            index=models.Index(fields=['name'], name='communicati_name_edff38_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationtagrelation',
            index=models.Index(fields=['communication', 'tag'], name='communicati_communi_e3f969_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communicationtagrelation',
            unique_together={('communication', 'tag')},
        ),
        migrations.AddIndex(
            model_name='communicationtemplate',
            index=models.Index(fields=['template_type', 'is_active'], name='communicati_templat_f2f780_idx'),
        ),
    ]
