# Generated by Django 4.2.7 on 2025-10-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='rating',
            field=models.IntegerField(null=True, blank=True, help_text='Rating from 1-5'),
        ),
    ]
