# Generated by Django 5.2.5 on 2025-10-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='rating',
            field=models.IntegerField(blank=True, help_text='Rating from 1-5', null=True),
        ),
    ]
