# Generated by Django 5.2.5 on 2025-09-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationresponse',
            name='is_resolution',
            field=models.BooleanField(default=False),
        ),
    ]
