# Generated by Django 5.2.5 on 2025-09-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_communicationresponse_is_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
