# Generated by Django 5.2.5 on 2025-10-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_alter_contact_options_contact_phone_contact_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
