# Generated by Django 5.2.5 on 2025-09-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_communication_order_id_communication_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='communicationresponse',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
